[package]
name = "krb5asn1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
hex = "0.4.3"
num-bigint = "0.4.4"
rasn = "0.14.0"
